export const menuItems = [
    {
        name: 'espresso',
        type: 'desayuno',
        price: '2990',
        category: 'cafe',
    },
    {
        name: 'espresso doble',
        type: 'desayuno',
        price: '2990',
        category: 'cafe',
    },
    {
        name: 'americano',
        type: 'desayuno',
        price: '2990',
        category: 'cafe',
    },
    {
        name: 'cortado',
        type: 'desayuno',
        price: '2990',
        category: 'cafe',
    },
    {
        name: 'capuccino',
        type: 'desayuno',
        price: '2990',
        category: 'cafe',
    },
    {
        name: 'latte',
        type: 'desayuno',
        price: '2990',
        category: 'cafe',
    },
    {
        name: 'mocaccino',
        type: 'desayuno',
        price: '2990',
        category: 'cafe',
    },
    {
        name: 'te verde',
        type: 'desayuno',
        price: '2990',
        category: 'te',
    },
    {
        name: 'te negro',
        type: 'desayuno',
        price: '2990',
        category: 'te',
    },
    {
        name: 'infusion de menta',
        type: 'desayuno',
        price: '2990',
        category: 'te',
    },
    {
        name: 'matcha',
        type: 'desayuno',
        price: '2990',
        category: 'te',
    },
    {
        name: 'chai',
        type: 'desayuno',
        price: '2990',
        category: 'te',
    },
    {
        name: 'chai latte',
        type: 'desayuno',
        price: '2990',
        category: 'te',
    },
    {
        name: 'croaissant o pan de chocolate',
        type: 'desayuno',
        price: '3990',
        category: 'dulce',
    },
    {
        name: 'granola natural y miel',
        description: 'Granola y yogurt con miel',
        type: 'desayuno',
        price: '3990',
        category: 'dulce',
    },
    {
        name: 'granola con frutas',
        description: 'Granola y yogurt con frutas de temporada',
        type: 'desayuno',
        price: '3990',
        category: 'dulce',
    },
    {
        name: 'tostadas de mermelada o miel',
        description: 'Tostadas con mermelada o miel',
        type: 'desayuno',
        price: '3450',
        category: 'dulce',
    },
    {
        name: 'panqueques simples y sirope de arce',
        description: 'Panqueque con jarabe de arce',
        type: 'desayuno',
        price: '4390',
        category: 'dulce',
    },
    {
        name: 'Tortilla con frutas',
        description: 'Tortilla con frutas de temorada',
        type: 'desayuno',
        price: '5590',
        category: 'dulce',
    },
    {
        name: 'Croissant templado de jamón emmental',
        description: 'Croissant caliente de jamón y queso',
        type: 'desayuno',
        price: '3990',
        category: 'salado',
    },
    {
        name: 'Huevos fritos',
        description: 'Huevos pasados por agua con pan y mantequilla',
        type: 'desayuno',
        price: '4450',
        category: 'salado',
    },
    {
        name: 'tostadas de aguacate o salmón',
        description: 'Tostada: aguacate o salmón',
        type: 'desayuno',
        price: '4990',
        category: 'salado',
    },
    {
        name: 'tostadas mixta de salmón y aguacate',
        description: 'Mezcla de aguacate y tostadas de salmón',
        type: 'desayuno',
        price: '4990',
        category: 'salado',
    },
    {
        name: 'plato continental: huevos, jamón y queso',
        description: 'Plato continental con quesos, jamones y huevos',
        type: 'desayuno',
        price: '4990',
        category: 'salado',
    },
    {
        name: 'machas a la parmesana',
        description: 'Queso parmesano, Vino blanco y Mantequilla (12 a 15 Uni.)',
        type: 'entradas',
        price: '16990',
    },
    {
        name: 'carpaccio de salmón',
        description: 'Alcaparras, queso, parmesano y un toque de aceite de oliva. (200gr)',
        type: 'entradas',
        price: '14990',
    },
    {
        name: 'ostiones a la parmesana',
        description: 'Queso parmesano, Vino blanco y Mantequilla (8 Uni.)',
        type: 'entradas',
        price: '18990',
    },
    {
        name: 'antipasto',
        description: 'Aceitunas, Fondos de Alcachofa, Quesos Mantecosos, Palmitos, Salame',
        type: 'entradas',
        price: '8990',
    },
    {
        name: 'gusteau salmón',
        description: 'Lechuga, Tomate, Aceitunas, trozos de salmón, Queso Parmesano y Dressing de Pesto',
        type: 'ensaladas',
        price: '10990',
    },
    {
        name: 'gusteau camarón',
        description: 'Lechuga, Tomate, Aceitunas, Camarón, Queso Parmesano y Dressing de Pesto',
        type: 'ensaladas',
        price: '10990',
    },
    {
        name: 'mixta',
        description: 'Lechuga, Palmito, Tomate, Aceituna.',
        type: 'ensaladas',
        price: '4990',
    },
    {
        name: 'huerto',
        description: 'Lechuga, Tomate, Choclo.',
        type: 'ensaladas',
        price: '4590',
    },
    {
        name: 'fetuccini de espinacas',
        description: '200gr',
        type: 'pastas',
        price: '8690',
    },
    {
        name: 'ravioli ricotta espinacas',
        description: '200gr',
        type: 'pastas',
        price: '9390',
    },
    {
        name: 'ravioli ricotta zapallo',
        description: '200gr',
        type: 'pastas',
        price: '9390',
    },
    {
        name: 'fetuccini de huevo',
        description: '200gr',
        type: 'pastas',
        price: '9390',
    },
    {
        name: 'ravioli ricotta pollo',
        description: '200gr',
        type: 'pastas',
        price: '9390',
    },
    {
        name: 'ravioli carne mechada',
        description: '200gr',
        type: 'pastas',
        price: '11390',
    },
    {
        name: 'ravioli 4 quesos',
        description: '200gr',
        type: 'pastas',
        price: '9390',
    },
    {
        name: 'ravioli salmón',
        description: '200gr',
        type: 'pastas',
        price: '9390',
    },
    {
        name: 'canelonni ricotta',
        description: '200gr',
        type: 'pastas',
        price: '10190',
    },
    {
        name: 'ñoquis de espinaca',
        description: '200gr',
        type: 'pastas',
        price: '10250',
    },
    {
        name: 'ñoquis de papa',
        description: '200gr',
        type: 'pastas',
        price: '9320',
    },
    {
        name: 'lasaña boloñesa',
        description: '200gr',
        type: 'pastas',
        price: '8990',
    },
    {
        name: 'lasaña boloñesa',
        description: '500gr',
        type: 'pastas',
        price: '11990',
    },
    {
        name: 'lasaña boloñesa',
        description: '2Kg',
        type: 'pastas',
        price: '22990',
    },
    {
        name: 'mix de pasta 2kg',
        description: 'Lasaña boloñesa, ñoqui, fetuccini, ravioli pollo. Bañado con salsa Boloñesa. (2Kg aprox.)',
        type: 'pastas',
        price: '27990',
    },
    {
        name: 'extra salsa',
        description: '2Kg',
        type: 'pastas',
        price: '3990',
    },
]


